Refatoração das classes, documentação de API e generalização dos cont…
RodolfoAndre/carango-bom-api-base pull request #2
Opened 2021-06-29 19:29 UTC by RodolfoAndre

…rollers

2021-06-29 19:32 UTC, FerdPires approved these changes

2021-06-29 19:36 UTC, FelipeTM approved these changes

2021-06-29 19:59 UTC, louisebahiense requested changes

2021-06-29 19:59 UTC, louisebahiense commented on src/main/java/br/com/caelum/carangobom/marca/Marca.java
> + * Classe responsável por gerencia a entidade marca
Aqui seria "gerenciar"

2021-06-29 19:59 UTC, louisebahiense commented on src/main/java/br/com/caelum/carangobom/marca/MarcaController.java
> +     * @param marcaService o seriviço de marcas
Typo em "serviço"

2021-06-29 19:59 UTC, louisebahiense commented on src/main/java/br/com/caelum/carangobom/marca/MarcaController.java
> +    public ResponseEntity<MarcaDto> obterMarcarPorId(@PathVariable Long id) {
Acho que aqui deveria ser "obterMarcaPorId" em vez de "marcar"

2021-06-29 19:59 UTC, louisebahiense commented on src/main/java/br/com/caelum/carangobom/marca/MarcaService.java
> + * Classe reponsável pela lógica de negócios de marcas
Typo no "responsável"

2021-06-29 19:59 UTC, louisebahiense commented on src/test/java/br/com/caelum/carangobom/marca/MarcaControllerTest.java
> +        MarcaDto audi = new MarcaDto(1l, "Audi");
Aqui não tenho certeza se o "1l" é case sensitive, mas observei que os outros estão "1L" em maiúsculo em vez de "1l"

2021-06-30 13:00 UTC, louisebsilva approved these changes

2021-06-30 13:12 UTC, merged