Autenticação e requisito de cadastro
RodolfoAndre/carango-bom-api-base pull request #6
Opened 2021-07-02 19:54 UTC by RodolfoAndre

2021-07-02 20:00 UTC, FelipeTM requested changes

2021-07-02 20:00 UTC, FelipeTM commented on src/main/java/br/com/caelum/carangobom/autenticacao/AutenticacaoService.java
> +	public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
Acredito que o parâmetro desse método deveria ser 'nome' e não 'emaill'

2021-07-02 20:11 UTC, FerdPires approved these changes

2021-07-05 14:41 UTC, FerdPires approved these changes

2021-07-05 14:46 UTC, FerdPires approved these changes

2021-07-05 14:46 UTC, FelipeTM approved these changes

2021-07-05 14:48 UTC, merged